format = """
[╭─](white)\
[](surface0)\
$os\
$username\
[](bg:blue fg:surface0)\
$directory\
[](fg:blue bg:peach)\
$git_branch\
$git_status\
[](fg:peach bg:green)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:green bg:teal)\
$docker_context\
[](fg:teal bg:purple)\
$time\
[ ](fg:purple)\
$line_break\
[╰─](white)$character
"""
# Sets user-defined palette
# Palettes must be defined _after_ this line
palette = "catppuccin_frappe"

[palettes.catppuccin_frappe]
rosewater = "#f2d5cf"
flamingo = "#eebebe"
pink = "#f4b8e4"
mauve = "#ca9ee6"
red = "#e78284"
maroon = "#ea999c"
peach = "#ef9f76"
yellow = "#e5c890"
green = "#a6d189"
teal = "#81c8be"
sky = "#99d1db"
sapphire = "#85c1dc"
blue = "#8caaee"
lavender = "#babbf1"
text = "#c6d0f5"
subtext1 = "#b5bfe2"
subtext0 = "#a5adce"
overlay2 = "#949cbb"
overlay1 = "#838ba7"
overlay0 = "#737994"
surface2 = "#626880"
surface1 = "#51576d"
surface0 = "#414559"
base = "#303446"
mantle = "#292c3c"
crust = "#232634"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
orange = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[os]
disabled = false
style = "bg:surface0 fg:text"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = ""
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:surface0 fg:text"
style_root = "bg:surface0 fg:text"
format = '[ $user ]($style)'

[directory]
style = "fg:mantle bg:blue"
format = "[  $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"documents" = "󰈙 "
"Downloads" = " "
"downloads" = " "
"Music" = "󰝚 "
"music" = "󰝚 "
"Pictures" = " "
"pictures" = " "
"Developer" = "󰲋 "
"developer" = "󰲋 "

[git_branch]
symbol = ""
format = '[[ $symbol $branch ](fg:base bg:peach)]($style)'

[git_status]
format = '[[$all_status$ahead_behind](fg:base bg:peach)]($style)'
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'


[nodejs]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:base bg:green)]($style)'

[c]
symbol = " "
style = "bg:green"
format = '[[ $symbol( $version) ](fg:base bg:green)]($style)'

[rust]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:base bg:green)]($style)'

[golang]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:base bg:green)]($style)'

[php]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:base bg:green)]($style)'

[java]
symbol = " "
style = "bg:green"
format = '[[ $symbol( $version) ](fg:base bg:green)]($style)'

[kotlin]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:base bg:green)]($style)'

[haskell]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:base bg:green)]($style)'

[python]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:base bg:green)]($style)'

[docker_context]
symbol = ""
style = "bg:mantle"
format = '[[ $symbol( $context) ](fg:base bg:teal)]($style)'

[time]
disabled = false
time_format = "%I:%M %p"
style = "bg:peach"
format = '[[  $time ](fg:mantle bg:purple)]($style)'

[line_break]
disabled = false

# [character]
# disabled = false
# success_symbol = '[](bold fg:green)'
# error_symbol = '[](bold fg:red)'
# vimcmd_symbol = '[](bold fg:creen)'
# vimcmd_replace_one_symbol = '[](bold fg:purple)'
# vimcmd_replace_symbol = '[](bold fg:purple)'
# vimcmd_visual_symbol = '[](bold fg:lavender)'
# command_timeout = 2000  # Timeout in milliseconds (default is 500)
